### ISSUE TITLE
Add instructions to setup dev environment

### ISSUE THREAD

**Issue by uecarlos** [icomefromthenet/BoltBookeMe#1]
I was trying to test if your extension would be a good base for a similar extension I need to build but I can't easily test it.

Do I need to setup custom content types? Please provide a short explanation on how to setup a dev environment.

I've obviously run composer and placed the extension in the proper directory. I'm having errors like "Unable to load rule types or match rule type to request value" while trying to add availability rule.

I'd like to contribute and test your extension.

Thanks for your work.

**Comment by icomefromthenet** [comment]
Its only 20% done , their is no public calendar and only few admin screens are working. 

It has rules engine and reservation engine and a lot of half started others. 

I am expecting to be working on it for another year.

**Comment by uecarlos** [comment]
It sure it's an ambitious project. I'll keep an eye on it but at this point in development it makes more sense to me to start from scratch a project on my own.

Best wishes.
